version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ele_network

  app:
    image: qmoo/ele-chart:latest
    ports:
      - "30800:30800"
    depends_on:
      - mongodb
    networks:
      - ele_network
    pull_policy:  always
volumes:
  mongodb_data:

networks:
  ele_network:
    driver: bridge